from enum import Enum

class Currency(Enum):
    # Format: (Index, Code, Name, Symbol, Decimal_Digits)
    USD = (0, "USD", "US Dollar", "$", 2)
    CAD = (1, "CAD", "Canadian Dollar", "CA$", 2)
    EUR = (2, "EUR", "Euro", "€", 2)
    AED = (3, "AED", "United Arab Emirates Dirham", "AED", 2)
    AFN = (4, "AFN", "Afghan Afghani", "Af", 0)
    ALL = (5, "ALL", "Albanian Lek", "Lek", 0)
    AMD = (6, "AMD", "Armenian Dram", "AMD", 0)
    ARS = (7, "ARS", "Argentine Peso", "AR$", 2)
    AUD = (8, "AUD", "Australian Dollar", "AU$", 2)
    AZN = (9, "AZN", "Azerbaijani Manat", "man.", 2)
    BAM = (10, "BAM", "Bosnia-Herzegovina Convertible Mark", "KM", 2)
    BDT = (11, "BDT", "Bangladeshi Taka", "Tk", 2)
    BGN = (12, "BGN", "Bulgarian Lev", "BGN", 2)
    BHD = (13, "BHD", "Bahraini Dinar", "BD", 3)
    BIF = (14, "BIF", "Burundian Franc", "FBu", 0)
    BND = (15, "BND", "Brunei Dollar", "BN$", 2)
    BOB = (16, "BOB", "Bolivian Boliviano", "Bs", 2)
    BRL = (17, "BRL", "Brazilian Real", "R$", 2)
    BWP = (18, "BWP", "Botswanan Pula", "P", 2)
    BYN = (19, "BYN", "Belarusian Ruble", "Br", 2)
    BZD = (20, "BZD", "Belize Dollar", "BZ$", 2)
    CDF = (21, "CDF", "Congolese Franc", "CDF", 2)
    CHF = (22, "CHF", "Swiss Franc", "CHF", 2)
    CLP = (23, "CLP", "Chilean Peso", "CL$", 0)
    CNY = (24, "CNY", "Chinese Yuan", "CN¥", 2)
    COP = (25, "COP", "Colombian Peso", "CO$", 0)
    CRC = (26, "CRC", "Costa Rican Colón", "₡", 0)
    CVE = (27, "CVE", "Cape Verdean Escudo", "CV$", 2)
    CZK = (28, "CZK", "Czech Republic Koruna", "Kč", 2)
    DJF = (29, "DJF", "Djiboutian Franc", "Fdj", 0)
    DKK = (30, "DKK", "Danish Krone", "kr", 2)
    DOP = (31, "DOP", "Dominican Peso", "RD$", 2)
    DZD = (32, "DZD", "Algerian Dinar", "DA", 2)
    EEK = (33, "EEK", "Estonian Kroon", "Ekr", 2)
    EGP = (34, "EGP", "Egyptian Pound", "EGP", 2)
    ERN = (35, "ERN", "Eritrean Nakfa", "Nfk", 2)
    ETB = (36, "ETB", "Ethiopian Birr", "Br", 2)
    GBP = (37, "GBP", "British Pound Sterling", "£", 2)
    GEL = (38, "GEL", "Georgian Lari", "GEL", 2)
    GHS = (39, "GHS", "Ghanaian Cedi", "GH₵", 2)
    GNF = (40, "GNF", "Guinean Franc", "FG", 0)
    GTQ = (41, "GTQ", "Guatemalan Quetzal", "GTQ", 2)
    HKD = (42, "HKD", "Hong Kong Dollar", "HK$", 2)
    HNL = (43, "HNL", "Honduran Lempira", "HNL", 2)
    HRK = (44, "HRK", "Croatian Kuna", "kn", 2)
    HUF = (45, "HUF", "Hungarian Forint", "Ft", 0)
    IDR = (46, "IDR", "Indonesian Rupiah", "Rp", 0)
    ILS = (47, "ILS", "Israeli New Sheqel", "₪", 2)
    INR = (48, "INR", "Indian Rupee", "Rs", 2)
    IQD = (49, "IQD", "Iraqi Dinar", "IQD", 0)
    IRR = (50, "IRR", "Iranian Rial", "IRR", 0)
    ISK = (51, "ISK", "Icelandic Króna", "Ikr", 0)
    JMD = (52, "JMD", "Jamaican Dollar", "J$", 2)
    JOD = (53, "JOD", "Jordanian Dinar", "JD", 3)
    JPY = (54, "JPY", "Japanese Yen", "¥", 0)
    KES = (55, "KES", "Kenyan Shilling", "Ksh", 2)
    KHR = (56, "KHR", "Cambodian Riel", "KHR", 2)
    KMF = (57, "KMF", "Comorian Franc", "CF", 0)
    KRW = (58, "KRW", "South Korean Won", "₩", 0)
    KWD = (59, "KWD", "Kuwaiti Dinar", "KD", 3)
    KZT = (60, "KZT", "Kazakhstani Tenge", "KZT", 2)
    LBP = (61, "LBP", "Lebanese Pound", "L.L.", 0)
    LKR = (62, "LKR", "Sri Lankan Rupee", "SLRs", 2)
    LTL = (63, "LTL", "Lithuanian Litas", "Lt", 2)
    LVL = (64, "LVL", "Latvian Lats", "Ls", 2)
    LYD = (65, "LYD", "Libyan Dinar", "LD", 3)
    MAD = (66, "MAD", "Moroccan Dirham", "MAD", 2)
    MDL = (67, "MDL", "Moldovan Leu", "MDL", 2)
    MGA = (68, "MGA", "Malagasy Ariary", "MGA", 0)
    MKD = (69, "MKD", "Macedonian Denar", "MKD", 2)
    MMK = (70, "MMK", "Myanma Kyat", "K", 0)
    MOP = (71, "MOP", "Macanese Pataca", "MOP$", 2)
    MUR = (72, "MUR", "Mauritian Rupee", "MURs", 0)
    MXN = (73, "MXN", "Mexican Peso", "MX$", 2)
    MYR = (74, "MYR", "Malaysian Ringgit", "RM", 2)
    MZN = (75, "MZN", "Mozambican Metical", "MTn", 2)
    NAD = (76, "NAD", "Namibian Dollar", "N$", 2)
    NGN = (77, "NGN", "Nigerian Naira", "₦", 2)
    NIO = (78, "NIO", "Nicaraguan Córdoba", "C$", 2)
    NOK = (79, "NOK", "Norwegian Krone", "Nkr", 2)
    NPR = (80, "NPR", "Nepalese Rupee", "NPRs", 2)
    NZD = (81, "NZD", "New Zealand Dollar", "NZ$", 2)
    OMR = (82, "OMR", "Omani Rial", "OMR", 3)
    PAB = (83, "PAB", "Panamanian Balboa", "B/.", 2)
    PEN = (84, "PEN", "Peruvian Nuevo Sol", "S/.", 2)
    PHP = (85, "PHP", "Philippine Peso", "₱", 2)
    PKR = (86, "PKR", "Pakistani Rupee", "PKRs", 2)
    PLN = (87, "PLN", "Polish Zloty", "zł", 2)
    PYG = (88, "PYG", "Paraguayan Guarani", "₲", 0)
    QAR = (89, "QAR", "Qatari Rial", "QR", 2)
    RON = (90, "RON", "Romanian Leu", "RON", 2)
    RSD = (91, "RSD", "Serbian Dinar", "din.", 0)
    RUB = (92, "RUB", "Russian Ruble", "RUB", 2)
    RWF = (93, "RWF", "Rwandan Franc", "RWF", 0)
    SAR = (94, "SAR", "Saudi Riyal", "SR", 2)
    SDG = (95, "SDG", "Sudanese Pound", "SDG", 2)
    SEK = (96, "SEK", "Swedish Krona", "Skr", 2)
    SGD = (97, "SGD", "Singapore Dollar", "S$", 2)
    SOS = (98, "SOS", "Somali Shilling", "Ssh", 0)
    SYP = (99, "SYP", "Syrian Pound", "SY£", 0)
    THB = (100, "THB", "Thai Baht", "฿", 2)
    TND = (101, "TND", "Tunisian Dinar", "DT", 3)
    TOP = (102, "TOP", "Tongan Paʻanga", "T$", 2)
    TRY = (103, "TRY", "Turkish Lira", "TL", 2)
    TTD = (104, "TTD", "Trinidad and Tobago Dollar", "TT$", 2)
    TWD = (105, "TWD", "New Taiwan Dollar", "NT$", 2)
    TZS = (106, "TZS", "Tanzanian Shilling", "TSh", 2)
    UAH = (107, "UAH", "Ukrainian Hryvnia", "₴", 2)
    UGX = (108, "UGX", "Ugandan Shilling", "USh", 0)
    UYU = (109, "UYU", "Uruguayan Peso", "$U", 2)
    UZS = (110, "UZS", "Uzbekistan Som", "UZS", 0)
    VEF = (111, "VEF", "Venezuelan Bolívar", "Bs.F.", 2)
    VND = (112, "VND", "Vietnamese Dong", "₫", 0)
    XAF = (113, "XAF", "CFA Franc BEAC", "FCFA", 0)
    XOF = (114, "XOF", "CFA Franc BCEAO", "CFA", 0)
    YER = (115, "YER", "Yemeni Rial", "YR", 0)
    ZAR = (116, "ZAR", "South African Rand", "R", 2)
    ZMK = (117, "ZMK", "Zambian Kwacha", "ZK", 0)
    ZWL = (118, "ZWL", "Zimbabwean Dollar", "ZWL$", 2)

    def __init__(self, index, code, currency_name, symbol, decimals):
        self._value_ = index
        self.code = code
        self.currency_name = currency_name
        self.symbol = symbol
        self.decimal_digits = decimals

# Example usage for formatting:
def format_currency(amount_integer, currency_enum):
    factor = 10 ** currency_enum.decimal_digits
    return f"{currency_enum.symbol}{amount_integer / factor:,.{currency_enum.decimal_digits}f}"

# print(format_currency(1050, Currency.USD)) # Output: $10.50
# print(format_currency(1050, Currency.JPY)) # Output: ¥1,050